[package]
name = "task"
version = "0.1.0"
edition = "2024"

[dependencies]
spinning_top = "0.3.0"
uart_16550 = "0.3.2"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }

[profile.dev]
panic = "abort"
debug = true

[profile.release]
panic = "abort"

