[package]
name = "jon_common"
version = "0.1.0"
edition = "2021"
authors = ["Matheus Filipe dos Santos Reinert"]

libjon = { path = "../../lib" }

[profile.dev]
panic = "abort"
debug = true

[profile.release]
panic = "abort"

[dependencies]
heapless = { version = "0.8.0" }

